use_frameworks!

target 'Purchasely_Example' do
	pod 'Purchasely', :git => 'git@github.com:Purchasely/Purchasely-iOS.git', :branch => 'fix/framework'
	#pod 'Purchasely', :path => '../' # :git => 'git@github.com:Purchasely/Purchasely-iOS.git'
end
